version: "3.9"
services:

  backend:
    build: backend/.
    #restart: always
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ../src/backend:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks: ['misquenet']

  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: '${LOCAL_PG_DIR}'
        target: '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_USER}'
    networks: ['misquenet']

networks: {misquenet: {}}
