-- SELECIONA OS MUNICPIOS QUE TEM O NOME IGUAL. MEDE A FREQUÊNCIA E RETORNA DECRESCENTE OS 10 MAIS REPETIDOS --
SELECT COUNT(NO_MUNICIPIO) AS FREQ, NO_MUNICIPIO FROM MUNICIPIOS GROUP BY NO_MUNICIPIO ORDER BY FREQ DESC LIMIT 10;

